{% set name = "voila-reveal" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 155d3e717ec87b7cba5eabd504e6486c1d94719fc7183a78ab6f5d432612c75f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - voila >=0.2.1,<0.3

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/reveal/index.html.j2"  # [unix]

about:
  home: https://github.com/voila-dashboards/voila-reveal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reveal template for voila'

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - mkcor
