{% set name = "voila-reveal" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6361988b96723574c94c50ba465831365a0a5b07e3a4b06d95e6551c627afab5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - voila >=0.2.1,<0.3

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/voila/templates/reveal/index.html.j2"  # [unix]

about:
  home: https://github.com/voila-dashboards/voila-reveal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reveal template for voila'

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - mkcor
